networks:
    forgejo:
        external: false

services:
    server:
        image: codeberg.org/forgejo/forgejo:11
        container_name: forgejo
        environment:
            - USER_UID=1000
            - USER_GID=1000
            - FORGEJO__database__DB_TYPE=postgres
            - FORGEJO__database__HOST=db:5432
            - FORGEJO__database__NAME=forgejo
            - FORGEJO__database__USER=forgejo
            - FORGEJO__database__PASSWD=forgejo
        restart: always
        networks:
            - forgejo
        volumes:
            - ./forgejo:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - '3000:3000'
            - '222:22'
        depends_on:
            - db

    db:
        image: postgres:14
        restart: always
        environment:
            - POSTGRES_USER=forgejo
            - POSTGRES_PASSWORD=forgejo
            - POSTGRES_DB=forgejo
        networks:
            - forgejo
        volumes:
            - ./postgres:/var/lib/postgresql/data

    woodpecker-server:
        image: woodpeckerci/woodpecker-server:v3
        container_name: woodpecker-server
        ports:
            - 8000:8000
        volumes:
            - woodpecker-server:/var/lib/woodpecker/
        environment:
            - WOODPECKER_OPEN=true
            - WOODPECKER_HOST=${WOODPECKER_HOST}
            - WOODPECKER_FORGEJO=true
            - WOODPECKER_FORGEJO_URL=${WOODPECKER_FORGEJO_URL}
            - WOODPECKER_FORGEJO_CLIENT=${WOODPECKER_FORGEJO_CLIENT}
            - WOODPECKER_FORGEJO_SECRET=${WOODPECKER_FORGEJO_SECRET}
            - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
        networks:
            - forgejo
        extra_hosts:
            - 'localhost:host-gateway'

    woodpecker-agent:
        image: woodpeckerci/woodpecker-agent:v3
        container_name: woodpecker-agent
        command: agent
        restart: always
        depends_on:
            - woodpecker-server
        volumes:
            - woodpecker-agent:/etc/woodpecker
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WOODPECKER_SERVER=${WOODPECKER_SERVER}
            - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
        networks:
            - forgejo

volumes:
    postgresql:
    woodpecker-server:
    woodpecker-agent:
