when:
  - event: push
    branch: main

steps:
  - name: solar-controlar
    image: python:3.11-bookworm
    when:
      - path: ['test/**', '.woodpecker/**']
    commands:
      - echo "Testing my Woodpecker pipeline..."
      - cd test
      - python3 test.py

  - name: build-docker
    image: docker:cli
    when:
      - path: [ 'odoo/Dockerfile', '.woodpecker/**']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd odoo
      - docker build .